In [1]:
import numpy as np
import pandas    as pd 

In [2]:
v = pd.read_csv(
                r'C:\\Users\\Chaconne\\Documents\\学业\\Projects\\RA_Simulation\\app_server\\config\\case_food_center_cov_matrix.csv',
                index_col='center_id').values

In [4]:
v[0]

array([ 1.13652995e+05, -3.74650106e+04,  1.52242514e+02,  1.02769076e+02,
        3.20117012e+04,  8.90385247e+01])

In [11]:
v2 = np.array([
    [113652.9946,	-37465.01062,	152.2425135,	102.7690763,	32011.70125,	89.03852468],
    [-37465.01062,	137223.4483,	100715.5776,	111.7531877,	-23449.91204,	103.1471614],
    [152.2425135,	100715.5776,	295682.0494,	151.5108562,	134.5415465,	-75566.93011],
    [102.7690763,	111.7531877,	151.5108562,	137073.65,	101.4975821,	94.87283555],
    [32011.70125,	-23449.91204,	134.5415465,	101.4975821,	100183.0197,	91.92860568],
    [89.03852468,	103.1471614,	-75566.93011,	94.87283555,	91.92860568,	120703.1537]
])

In [12]:
v2[0] == v[0]

array([ True,  True,  True,  True,  True,  True])

In [12]:
d = {'1':2, '3':4, '7':8}


seq = []
for i in range(1000):
    it_res = []
    for k in d.values():
        it_res.append(k)
    seq.append(it_res)

same = True
for i in range(1, len(seq)):
    same = seq[i - 1] == seq[i]

seq[:5], same

([[2, 4, 8], [2, 4, 8], [2, 4, 8], [2, 4, 8], [2, 4, 8]], True)

In [19]:
type(d.values())

dict_values

In [35]:


round(0.9)

l = [2] * 3 
l2 = np.repeat(-1,3)
np.fmax(l, -1)

array([2, 2, 2])

In [36]:
{'1':[], '2':333, 4:0}

{'1': [], '2': 333, 4: 0}